import doctorImg from "../profile/doctor.jpg";

const patientList = [
  {
    familyName: "Belloumi",
    firstName: "Lekhder",
    profilePicture: doctorImg,
    nextAppointment: "16 Jun - 1:00PM",
    lastVisit: "2024/05/04",
    diagnosis: "Ear Infection",
    status: "active",
  },
  {
    familyName: "Belloumi",
    firstName: "Lekhder",
    profilePicture: doctorImg,
    nextAppointment: "",
    lastVisit: "2024/05/01",
    diagnosis: "Ear Infection",
    status: "non-active",
  },
  {
    familyName: "Belloumi",
    firstName: "Lekhder",
    profilePicture: doctorImg,
    nextAppointment: "16 Jun - 1:00PM",
    lastVisit: "2024/05/01",
    diagnosis: "Ear Infection",
    status: "new",
  },
  {
    familyName: "Belloumi",
    firstName: "Lekhder",
    profilePicture: doctorImg,
    nextAppointment: "16 Jun - 1:00PM",
    lastVisit: "2024/05/01",
    diagnosis: "Ear Infection",
    status: "active",
  },
  {
    familyName: "Belloumi",
    firstName: "Lekhder",
    profilePicture: doctorImg,
    nextAppointment: "16 Jun - 1:00PM",
    lastVisit: "2024/05/01",
    diagnosis: "Ear Infection",
    status: "active",
  },
  {
    familyName: "Belloumi",
    firstName: "Lekhder",
    profilePicture: doctorImg,
    nextAppointment: "16 Jun - 1:00PM",
    lastVisit: "2024/05/01",
    diagnosis: "Ear Infection",
    status: "active",
  },
  {
    familyName: "Belloumi",
    firstName: "Lekhder",
    profilePicture: doctorImg,
    nextAppointment: "16 Jun - 1:00PM",
    lastVisit: "2024/05/01",
    diagnosis: "Ear Infection",
    status: "active",
  },
  {
    familyName: "Belloumi",
    firstName: "Lekhder",
    profilePicture: doctorImg,
    nextAppointment: "16 Jun - 1:00PM",
    lastVisit: "2024/05/01",
    diagnosis: "Ear Infection",
    status: "active",
  },
  {
    familyName: "Belloumi",
    firstName: "Lekhder",
    profilePicture: doctorImg,
    nextAppointment: "16 Jun - 1:00PM",
    lastVisit: "2024/05/01",
    diagnosis: "Ear Infection",
    status: "active",
  },
  {
    familyName: "Belloumi",
    firstName: "Lekhder",
    profilePicture: doctorImg,
    nextAppointment: "16 Jun - 1:00PM",
    lastVisit: "2024/05/01",
    diagnosis: "Ear Infection",
    status: "active",
  },
  {
    familyName: "Belloumi",
    firstName: "Lekhder",
    profilePicture: doctorImg,
    nextAppointment: "16 Jun - 1:00PM",
    lastVisit: "2024/05/01",
    diagnosis: "Ear Infection",
    status: "active",
  },
  {
    familyName: "Belloumi",
    firstName: "Lekhder",
    profilePicture: doctorImg,
    nextAppointment: "16 Jun - 1:00PM",
    lastVisit: "2024/05/01",
    diagnosis: "Ear Infection",
    status: "active",
  },
  {
    familyName: "Belloumi",
    firstName: "Lekhder",
    profilePicture: doctorImg,
    nextAppointment: "16 Jun - 1:00PM",
    lastVisit: "2024/05/01",
    diagnosis: "Ear Infection",
    status: "active",
  },
];

export default patientList;
