import doctorImg from "../profile/doctor.jpg";

const patientList = [
  {
    familyName: "Belloumi",
    firstName: "Lekhder",
    profilePicture: "https://xsgames.co/randomusers/assets/avatars/male/60.jpg",
    nextAppointment: "16 Jun - 1:00PM",
    lastVisit: "2024/05/04",
    diagnosis: "Ear Infection",
    status: "active",
  },
  {
    familyName: "Abdelmajid",
    firstName: "Tebboune",
    profilePicture: "https://xsgames.co/randomusers/assets/avatars/male/61.jpg",
    nextAppointment: "",
    lastVisit: "2024/05/01",
    diagnosis: "Ear Infection",
    status: "non-active",
  },
  {
    familyName: "Radouane",
    firstName: "Mostafa",
    profilePicture: "https://xsgames.co/randomusers/assets/avatars/male/62.jpg",
    nextAppointment: "16 Jun - 1:00PM",
    lastVisit: "2024/05/01",
    diagnosis: "Ear Infection",
    status: "new",
  },
  {
    familyName: "Yousra",
    firstName: "Youli",
    profilePicture:
      "https://xsgames.co/randomusers/assets/avatars/female/48.jpg",
    nextAppointment: "16 Jun - 1:00PM",
    lastVisit: "2024/05/01",
    diagnosis: "Ear Infection",
    status: "active",
  },
  {
    familyName: "Amine",
    firstName: "Kouider",
    profilePicture: "https://xsgames.co/randomusers/assets/avatars/male/15.jpg",
    nextAppointment: "16 Jun - 1:00PM",
    lastVisit: "2024/05/01",
    diagnosis: "Ear Infection",
    status: "active",
  },
  {
    familyName: "Ali",
    firstName: "Benchikh",
    profilePicture: "https://xsgames.co/randomusers/assets/avatars/male/25.jpg",
    nextAppointment: "16 Jun - 1:00PM",
    lastVisit: "2024/05/01",
    diagnosis: "Ear Infection",
    status: "active",
  },
  {
    familyName: "Aisha",
    firstName: "Boulenoir",
    profilePicture:
      "https://xsgames.co/randomusers/assets/avatars/female/22.jpg",
    nextAppointment: "16 Jun - 1:00PM",
    lastVisit: "2024/05/01",
    diagnosis: "Ear Infection",
    status: "active",
  },
  {
    familyName: "Harrag",
    firstName: "Moussa",
    profilePicture: "https://xsgames.co/randomusers/assets/avatars/male/22.jpg",
    nextAppointment: "16 Jun - 1:00PM",
    lastVisit: "2024/05/01",
    diagnosis: "Ear Infection",
    status: "active",
  },
  {
    familyName: "Anter",
    firstName: "Yahia",
    profilePicture: doctorImg,
    nextAppointment: "16 Jun - 1:00PM",
    lastVisit: "2024/05/01",
    diagnosis: "Ear Infection",
    status: "active",
  },
  {
    familyName: "Asmaa",
    firstName: "Mouloui",
    profilePicture: doctorImg,
    nextAppointment: "16 Jun - 1:00PM",
    lastVisit: "2024/05/01",
    diagnosis: "Ear Infection",
    status: "active",
  },
  {
    familyName: "Miloud",
    firstName: "Ouahab",
    profilePicture: doctorImg,
    nextAppointment: "16 Jun - 1:00PM",
    lastVisit: "2024/05/01",
    diagnosis: "Ear Infection",
    status: "active",
  },
  {
    familyName: "Mohamed",
    firstName: "Tlouiwat",
    profilePicture: doctorImg,
    nextAppointment: "16 Jun - 1:00PM",
    lastVisit: "2024/05/01",
    diagnosis: "Ear Infection",
    status: "active",
  },
  {
    familyName: "Masoud",
    firstName: "Nabil",
    profilePicture: doctorImg,
    nextAppointment: "16 Jun - 1:00PM",
    lastVisit: "2024/05/01",
    diagnosis: "Ear Infection",
    status: "active",
  },
];

export default patientList;
